module.exports = (sequelize, Secuelize) => {
	return sequelize.define('transaction', {
		id: {
			type: Secuelize.INTEGER,
			primaryKey: true,
			autoIncrement: true,
		},
		name: {
			type: Secuelize.STRING,
		},
		description: {
			type: Secuelize.STRING,
		},
		amount: {
			type: Secuelize.INTEGER,
		},
		category: {
			type: Secuelize.ENUM,
			values: [
				'Income',
				'Housing',
				'Transportation',
				'Food',
				'Utilities',
				'Personal',
				'Entertainment',
				'Insurance_HealthCare',
				'Education',
				'Debt_Payments',
				'Giving',
				'Saving',
			],
		},
		subcategory: {
			type: Secuelize.ENUM,
			values: [
				'Salary',
				'BonusesCommission',
				'InvestmentIncome',
				'InterestIncome',
				'SideHustleIncome',
				'ChildSupport',
				'Alimony',
				'CreditCardRewards',

				'Mortgage',
				'Rent',
				'PropertyTaxes',
				'HomeownerInsurance',
				'HomeMaintenanceRepairs',
				'HomeImprovement',

				'CarPayment',
				'CarMaintenanceRepairs',
				'CarInsurance',
				'Fuel',
				'PublicTransportation',
				'RideSharing',
				'Tolls',
				'ParkingFees',
				'VehicleRegistrationInspection',

				'Groceries',
				'Restaurants',
				'WorkLunches',
				'TakeOut',
				'FastFood',

				'Electricity',
				'Water',
				'NaturalGas',
				'GarbageCollection',
				'Phone',
				'Cable',
				'Internet',

				'Clothing',
				'Shoes',
				'PersonalHygiene',
				'HouseholdSupplies',
				'ChildCare',
				'HairCuts',
				'GymMembership',
				'HomeFurnishings',

				'MoviesEvents',
				'SubscriptionServices',
				'Vacations',
				'Hobbies',
				'DateNights',

				'HealthInsurance',
				'DentalInsurance',
				'VisionInsurance',
				'LifeInsurance',
				'DisabilityInsurance',
				'PrescriptionsMedicines',
				'OutHealthcareExpenses',

				'Tuition',
				'ExtracurricularActivities',
				'Books',
				'SchoolSupplies',
				'Uniforms',
				'Registration',
				'OtherFees',

				'StudentLoans',
				'CreditCards',
				'PersonalLoans',
				'InstallmentLoans',

				'Religious',
				'Charities',
				'Gifts',

				'RetirementAccounts',
				'EmergencyFund',
				'EducationFund',
				'SinkingFund',
			],
		},
	})
}
